//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.10.10 at 08:53:59 AM ICT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.cyber.com/ws/")
package com.cyber.ws;
